# Generated by Django 5.1.15 on 2026-08-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for correction')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='bookings.booking')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('routed_to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='core.department')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
