# Generated by Django 5.1.15 on 2026-08-03 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('booked', 'Booked'), ('maintenance', 'Under maintenance'), ('cleaning', 'Cleaning in progress'), ('closed', 'Closed')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_changes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='rooms.room')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['room', '-timestamp'], name='usage_usage_room_id_0ef2c6_idx')],
            },
        ),
    ]
