# Generated by Django 5.1.15 on 2026-09-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdraft',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
