# Generated by Django 5.1.15 on 2026-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_default_suitability_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
